name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: backend

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # CI - Validate backend dependencies
      - name: Validate backend dependencies
        run: npm install

      # Configure AWS credentials via OIDC
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::141701955118:role/GitHub-OIDC-Role
          aws-region: us-east-1
          audience: GitHub-OIDC-Provider


      - name: Deploy Backend
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/3-Tier-Applicstion-backend/backend
            git fetch origin main
            git reset --hard origin/main
            npm install --omit=dev
            pm2 restart backend
            pm2 save